# docker-compose.yml
version: "2"
services:
  web:
    image: nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - $NGINX_PORT
    volumes:
      - "./public:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"    
    depends_on:
      - php    
    ports: 
      - "9333:80"
  php:
    build:
      context: php
      dockerfile: Dockerfile
#    image: drupal:$DRUPAL_TAG
    container_name: "${PROJECT_NAME}_drupal"
    volumes:
      - "./public:/var/www/html"
    restart: always
    depends_on:
      - mariadb   
    ports: 
      - "9005:9005"
  node:
    build:
      context: nodejs
      dockerfile: Dockerfile
#    image: drupal:$DRUPAL_TAG
    container_name: "${PROJECT_NAME}_nodejs"
    volumes:
      - "./public:/app"
#  mysql:
#      image: mysql:$MYSQL_TAG
#      container_name: "${PROJECT_NAME}_mysql"
#      entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
#      environment:
#        MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
#        MYSQL_USER: $DB_USER
#        MYSQL_PASSWORD: $DB_PASSWORD
#        MYSQL_DATABASE: $DB_NAME
#      volumes:
#        - "./public:/var/www/html"
#        - "./drupal/mysql:/var/lib/mysql"
#      restart: always
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
   # volumes:
   #   - "./public:/var/www/html"
   #   - "./drupal/mysql:/var/lib/mysql"
    restart: always
